import Head from "next/head";
import Image from "next/image";
import React from "react";
import { useMoralis } from "react-moralis";
import logo from "../Assets/metamask.svg";
export default function Index() {
  const { authenticate, isAuthenticated, logout, user } = useMoralis();

  return (
    <div>
      <div className="">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {isAuthenticated ? (
          <div
            style={{
              color: "white",
              fontSize: "1rem",
              fontWeight: "lighter",
              textAlign: "center",
            }}
          >
            <h2>Welcome {user.get("username")}</h2>
            <h2>Your wallet address is {user.get("ethAddress")}</h2>
            <button
              style={{
                backgroundColor: "lavender",
                border: "none",
                borderRadius: "5px",
                padding: "10px",
                fontSize: "1rem",
              }}
              onClick={logout}
            >
              Logout
            </button>
          </div>
        ) : (
          <div className="body">
            <div className="xbox" data-char="M">
              M
              <div className="inside">
                <button
                  style={{
                    backgroundColor: "transparent",
                    border: "none",
                    outline: "none",
                    cursor: "pointer",
                  }}
                  onClick={authenticate}
                >
                  <Image src={logo} alt="MetaMask" width={150} height={150} />
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
